apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: app-pod-id
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=03228871-7f68-4594-b208-2d8207a65428
      - --clientid=c26f1355-efdc-4422-9de2-0783cf8224da
      - --resourcegroup=nzaplakspodid-rg
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux
